"""One-time migration of the unaccepted M1.1 drafts into workbench records.

Input: litepaper snapshot SRC-LP20 and the M1.1 draft package SRC-M1-DRAFTS.
Output: importable tiddler JSON. After import the workbench is authoritative.
Usage: python3 m1_records.py [--pilot]   (--pilot emits only MFS, honesty
scoring and operator-entry records plus what they link to.)
"""

from __future__ import annotations

import json
import sys

R = []
BASE = dict(stage="M1", introduced_by="M1.1", last_changed_by="M1.1")
DRAFT_MAP = "litepaper-baseline-map.md"
DRAFT_GE = "growth-and-entry-assessment.md"
DRAFT_VD = "validator-decision-map.csv"
DRAFT_EX = "experiments/m1/baseline-accounting"


def rec(rid, rt, caption, **f):
    t = {"title": rid, "record_type": rt, "caption": caption, "tags": "FX" if rt == "FX" else f"Record {rt}", **BASE}
    for k, v in f.items():
        if v not in (None, ""):
            t[k] = v
    R.append(t)


def src(lines):
    return f"SRC-LP20 {lines}"


# ================================================================== LP concepts

LP = [
    ("LP-01", "Agent layer, network scope and discovery", "mechanism", "explicit",
     "Livepeer is framed as an open video agent platform: protocol, network and an MCP-accessible agent that routes compute demand and fees through the network. The network should expose every known media AI capability, including API passthrough.",
     "L15-29", "customer operator"),
    ("LP-02", "Design principles", "principle", "explicit",
     "Four principles guide the design: rewards follow real work, every role does active work, governance can adjust the incentive model, and simplicity is a feature.",
     "L31-38", "operator delegator validator governance"),
    ("LP-03", "Permissionless node registry and operator entry", "mechanism", "explicit",
     "Any address can register as a node at any time with no fixed LPT bond and no node count cap. Nodes are listed in an onchain registry and advertise capabilities, regions and price.",
     "L51-53, L175-181, L219", "operator customer"),
    ("LP-04", "Min-Fee-Stake (MFS)", "mechanism", "explicit",
     "A node's share of inflationary LPT rewards is the lesser of its share of network fees and its share of network stake; fees themselves are never capped. The appendix separately describes node emissions as proportional to work completed, weighted by the validator multiplier.",
     "L55-63, L69, L220, L231", "operator delegator"),
    ("LP-05", "Delegation", "mechanism", "explicit",
     "Delegators bond to nodes with today's mechanics; the stake behind a node sets its reward ceiling, so active delegators are expected to move stake toward high-fee understaked nodes. Stake also elects validators and votes in governance.",
     "L65-77", "delegator operator"),
    ("LP-06", "Validator set: top-N opt-in", "mechanism", "explicit",
     "The top N nodes by total stake may opt in as validators; node operators and validators are the same participants. A declined slot passes to the next-highest-staked registered node.",
     "L40-49, L73, L79-84, L221", "validator operator delegator"),
    ("LP-07", "Honesty score and median multiplier", "mechanism", "explicit",
     "Each active validator may score every node from 0.0 to 1.0, and the median scales the node's MFS-eligible reward. The score targets dishonesty such as self-dealing, fee fabrication or incorrect results, not service quality.",
     "L42-49, L86-88", "validator operator"),
    ("LP-08", "21-round unbonding and transferBond", "mechanism", "explicit",
     "Unbonding for all stake behind a node rises to 21 rounds. transferBond must be eliminated or delayed by the same period, which the paper says is not a settled tradeoff.",
     "L92-105, L198, L223", "delegator operator"),
    ("LP-09", "7-round reward delay and claim-time scoring", "mechanism", "explicit",
     "Rewards for round n become claimable at n+7, and the payout uses the median score current at claim time. The delay is meant to let validators catch single-round fee spikes.",
     "L107-109, L181, L224", "operator validator"),
    ("LP-10", "USDC payments", "mechanism", "explicit",
     "Network payments and pricing move from ETH to USDC; nodes price services in USD.",
     "L111-113, L225", "customer operator"),
    ("LP-11", "Node/network fee split and buy-back-and-burn (BME)", "mechanism", "explicit",
     "Half of each USDC fee goes to the node and half buys LPT on the market, all of which is burned. Rewards come from a separate mint; buyback execution design is left outside the paper.",
     "L115-125, L207-211, L226-230, L237-246", "operator customer governance"),
    ("LP-12", "Emissions schedule", "parameter-set", "open-draft",
     "The section is an open idea draft listing three emissions concepts, plus an AI-enabled elaboration of the first with a $50M/year cap. No concept is selected.",
     "L128-172, L194, L234-235", "governance"),
    ("LP-13", "Emission allocation and validator compensation", "parameter-set", "proposed-value",
     "Round emissions are proposed to split 94% to nodes, 1% to validators and their delegators, and 5% to the treasury. Main text and appendix describe the validator split differently.",
     "L84, L212, L231-233", "operator validator delegator governance"),
    ("LP-14", "Governance authority and the swappable score contract", "mechanism", "explicit",
     "Parameters are governance-adjustable, and the contract implementing RewardMultiplier scores is a governance-swappable address. A validator constitution is referenced but not written.",
     "L37, L75, L90, L200, L215-235", "governance validator"),
    ("LP-15", "Explicit exclusions", "exclusion", "explicit",
     "The design excludes a minimum self-stake, a separate migration or election event, and a new-node reward ramp.",
     "L175-181", "operator"),
    ("LP-16", "Open questions in the paper", "open-question", "explicit",
     "The paper lists five unresolved questions: payment security with unlimited nodes, a price oracle for emissions, minimum validator participation, transferBond versus active delegation, and the validator constitution.",
     "L189-200", "governance validator delegator"),
]
for rid, cap, kind, status, inp, lines, parts in LP:
    rec(rid, "LP", cap, kind=kind, status=status, in_paper=inp, source_ref=src(lines), participants=parts)
R[3]["formula"] = "`reward % = min(fee % of network total, stake % of network total)` (L58). Reconstructed node entitlement: [[EX-01]]."
R[6]["formula"] = "Node receives median(active validator scores) × MFS-eligible reward (L86)."

# ================================================================== RL provisions
# (id, caption, concepts, kind, status, in_paper, lines, value, unit, gov, participants)
RL = [
    ("RL-01", "Three layers: protocol, network, agent", "LP-01", "rule", "explicit",
     "The protocol handles incentives, payments and security; the network exposes media compute; the agent is reachable via MCP and routes demand and fees through the network.", "L23-27"),
    ("RL-02", "Network scope includes API passthrough", "LP-01 LP-03", "rule", "explicit",
     "Besides GPU-hosted open models, the network supports API passthrough to third-party services and other media compute such as transcoding and captioning.", "L26"),
    ("RL-03", "Principle: rewards follow real work", "LP-02 LP-04", "principle", "explicit",
     "Fees for honest work, not just stake, should be the primary basis for inflationary rewards during bootstrapping.", "L35"),
    ("RL-04", "Principle: every role does active work", "LP-02 LP-05", "principle", "explicit",
     "A role that exists purely for stake-based rent seeking should become one that actively adds value.", "L36"),
    ("RL-05", "Principle: governance can adjust the model", "LP-02 LP-14", "principle", "explicit",
     "Include parameters that let the community maintain a fee/mint balance as conditions change.", "L37"),
    ("RL-06", "Principle: simplicity", "LP-02", "principle", "explicit",
     "Prefer mechanisms operators and delegators can reason about over theoretically elegant ones.", "L38"),
    ("RL-07", "Open registration without a bond", "LP-03", "rule", "explicit",
     "Any address can register as a node operator at any time with no fixed LPT bond.", "L53"),
    ("RL-08", "Onchain registry and adverts", "LP-03 LP-01", "rule", "explicit",
     "Nodes are listed in the onchain registry used for discovery and advertise capabilities, regions and price.", "L53"),
    ("RL-09", "Node operator cap", "LP-03", "parameter", "explicit",
     "No cap on the number of nodes, replacing the 100-orchestrator limit.", "L53, L219", "none", "nodes", "n/a"),
    ("RL-10", "MFS formula", "LP-04", "formula", "explicit",
     "A node's reward percentage is the minimum of its fee percentage and its stake percentage of network totals.", "L57-58, L220", "min(fee %, stake %)", "", "no",
     "`reward % = min(fee % of network total, stake % of network total)`"),
    ("RL-11", "Fees uncapped; stake caps only inflation", "LP-04 LP-03", "rule", "explicit",
     "Fees are never capped; only the inflationary LPT reward attached to them is capped by self and delegated stake.", "L61"),
    ("RL-12", "Fee and stake measurement windows", "LP-04", "parameter", "explicit",
     "The underlying stake and fee measurement windows are governance-adjustable; no window is chosen.", "L220", "not specified", "", "yes"),
    ("RL-13", "Appendix: node emissions proportional to work", "LP-04 LP-13", "formula", "explicit",
     "NodeEmissionShare is distributed proportionally to each node's share of work completed in the round, weighted by its aggregate validator multiplier.", "L231"),
    ("RL-14", "MFS worked example", "LP-04 LP-05", "illustration", "illustrative",
     "10% of fees with 2% of stake earns 2%; 5% of fees with 5% of stake earns 5%.", "L61, L69"),
    ("RL-15", "Delegation keeps today's mechanics", "LP-05", "rule", "explicit",
     "Delegators stake toward nodes with the same bonding, unbonding and reward/fee-cut mechanics as today.", "L67"),
    ("RL-16", "Stake sets a node's reward ceiling", "LP-05 LP-04", "rule", "explicit",
     "A node's rewards stay capped at its stake share unless it attracts more stake; delegators can raise the ceiling of an understaked high-fee node.", "L69"),
    ("RL-17", "Stake votes in governance and treasury", "LP-05 LP-14", "rule", "explicit",
     "Stake continues to carry weight in governance and treasury votes.", "L75"),
    ("RL-18", "Operators and validators are one participant set", "LP-06", "rule", "explicit",
     "Node operators and validators are the same set of participants; the top nodes by stake inherit the validator role.", "L49"),
    ("RL-19", "Validator eligibility: top N by stake, opt-in", "LP-06", "rule", "explicit",
     "The top N node operators by total self plus delegated stake are eligible and become active validators only by registering.", "L81, L221"),
    ("RL-20", "ValidatorSetSize", "LP-06", "parameter", "proposed-value",
     "Proposed starting N for the validator set.", "L81, L221", "33", "validators", "yes"),
    ("RL-21", "Declined slot passes to next registered node", "LP-06", "rule", "explicit",
     "A top-ranked node can decline; the next-highest-staked registered node fills the slot.", "L221"),
    ("RL-22", "Main text: validator reward 1% of post-BME mint", "LP-06 LP-13", "formula", "proposed-value",
     "Active validators earn a ValidatorRewardShare of 1% of the post-BME LPT mint for the period, split among all currently active validators.", "L84", "1%", "of post-BME mint", "unstated"),
    ("RL-23", "Validators score every node 0.0-1.0", "LP-07", "rule", "explicit",
     "Each active validator can assign every node a RewardMultiplier score from 0.0 to 1.0.", "L86"),
    ("RL-24", "Median score scales MFS-eligible reward", "LP-07 LP-04", "formula", "explicit",
     "The median score across active validators sets the fraction of a node's MFS-eligible reward it receives.", "L86", "", "", "", "payout = median(scores) × MFS-eligible reward"),
    ("RL-25", "Score targets dishonesty, not service quality", "LP-07", "rule", "explicit",
     "The score exists to catch dishonest behavior such as self-dealing, fee fabrication or serving incorrect results. Legitimate limits such as regional coverage or model availability should not be penalized; the score does not grade quality of service.", "L86"),
    ("RL-26", "Evidence tooling as a public good", "LP-07 LP-14", "rule", "explicit",
     "Testing frameworks, monitoring, dashboards and anomaly detection should be funded as a public good; validators vote on that published evidence or other surfaced criteria.", "L88"),
    ("RL-27", "UnbondingPeriod", "LP-08", "parameter", "proposed-value",
     "Unbonding for all stake behind a node, self or delegated, including bond transfers.", "L94, L223", "21", "rounds", "yes"),
    ("RL-28", "transferBond option: eliminate", "LP-08", "alternative", "explicit",
     "transferBond is eliminated so stake cannot escape a pending reward reduction.", "L103"),
    ("RL-29", "transferBond option: delay 21 rounds", "LP-08", "alternative", "explicit",
     "transferBond is subjected to a 21-round wait before applying to the new node; the appendix lists 21 rounds including transfers.", "L103, L223"),
    ("RL-30", "RewardsDelayPeriod", "LP-09", "parameter", "proposed-value",
     "Rewards for round n become claimable at round n+7.", "L109, L224", "7", "rounds", "yes"),
    ("RL-31", "Claim-time median applies", "LP-09 LP-07", "rule", "explicit",
     "The payout uses the median RewardMultiplier current at the time of claiming.", "L109, L224"),
    ("RL-32", "Payment currency USDC, USD pricing", "LP-10", "parameter", "explicit",
     "Nodes price services in USD and are paid in USDC instead of ETH.", "L113, L225", "USDC", "", "n/a"),
    ("RL-33", "BMENodeCut", "LP-11", "parameter", "proposed-value",
     "Share of USDC fees paid directly to the node.", "L119, L226", "50%", "of gross fees", "yes"),
    ("RL-34", "BMENetworkFee", "LP-11", "parameter", "proposed-value",
     "Share of USDC fees diverted to BME to buy and burn LPT.", "L119, L227", "50%", "of gross fees", "yes"),
    ("RL-35", "Identity: fee cuts sum to 100%", "LP-11", "formula", "explicit",
     "BMENodeCut and BMENetworkFee together are 100% of gross fees.", "L210", "", "", "", "`BMENodeCut + BMENetworkFee = 100% of gross fees`"),
    ("RL-36", "BMEBurnPercentage", "LP-11", "parameter", "proposed-value",
     "Share of purchased LPT that is burned.", "L121, L228", "100%", "of purchased LPT", "yes"),
    ("RL-37", "Identity: purchased-LPT cuts sum to 100%", "LP-11", "formula", "explicit",
     "Burn percentage, treasury cut and validator cut together are 100% of purchased LPT.", "L211", "", "", "", "`BMEBurnPercentage + BMETreasuryCut + BMEValidatorCut = 100% of purchased LPT`"),
    ("RL-38", "BMETreasuryCut", "LP-11", "parameter", "proposed-value",
     "Share of the post-burn fee-side pool to the treasury; always zero at 100% burn.", "L229", "0%", "of post-burn pool", "yes"),
    ("RL-39", "BMEValidatorCut", "LP-11", "parameter", "proposed-value",
     "Share of the post-burn fee-side pool to validators and their delegators; inactive at 100% burn.", "L230", "0%", "of post-burn pool", "yes"),
    ("RL-40", "Rewards come from a separate mint", "LP-11 LP-12", "rule", "explicit",
     "Inflationary rewards are funded by an independently governed mint, not by recycling bought-back LPT.", "L121, L228"),
    ("RL-41", "Buyback execution left outside the paper", "LP-11 LP-16", "open-question", "explicit",
     "Low-slippage, manipulation-resistant DEX purchase design needs further research; example parameters are given but the mechanism is out of scope.", "L125, L239"),
    ("RL-42", "BMELiquidityPool", "LP-11", "parameter", "illustrative",
     "Onchain address of the primary LPT pool used for purchases, governable.", "L243", "TBD", "", "yes"),
    ("RL-43", "BMETWAPInterval", "LP-11", "parameter", "illustrative",
     "Look-back window for the TWAP reference price before a buy.", "L244", "3600", "seconds", "unstated"),
    ("RL-44", "BMEBuyFrequency", "LP-11", "parameter", "illustrative",
     "How often accumulated network-fee proceeds are deployed to buy LPT.", "L245", "1", "round", "unstated"),
    ("RL-45", "BMEMaxSlippage", "LP-11", "parameter", "illustrative",
     "Maximum deviation from TWAP before a buy reverts and fees roll over.", "L246", "1%", "", "unstated"),
    ("RL-46", "BME objective: burn reaches equilibrium with mint", "LP-11 LP-12", "objective", "explicit",
     "On a predictable schedule, usage-driven burn should reach equilibrium with emissions-driven mint, so supply is capped and predictable over time.", "L121"),
    ("RL-47", "Emissions concept 1: declining ratio to fees", "LP-12", "alternative", "open-draft",
     "Emissions start at 3200% of fees per year and halve every two years, reaching equilibrium with BME around year 10/11.", "L134, L234", "3200% halving every 2 years", "of annual fees", "yes"),
    ("RL-48", "Emissions concept 2: fee-offset USD cap", "LP-12", "alternative", "open-draft",
     "As concept 1, but cap total mint so that fees plus mint do not exceed the current value of about $35M.", "L135", "$35M", "fees + mint per year", "unstated"),
    ("RL-49", "Emissions concept 3: bounded participation adjustment", "LP-12", "alternative", "open-draft",
     "Keep participation-based inflation adjustment with a 2% floor and 10% ceiling per year.", "L136", "2%-10%", "annual inflation", "unstated"),
    ("RL-50", "Annual emissions hard cap", "LP-12", "parameter", "open-draft",
     "The AI-enabled draft of concept 1 adds a USD-equivalent annual cap as a guardrail.", "L140, L156-172, L235", "$50M", "USD-equivalent per year", "yes"),
    ("RL-51", "Reported current emissions-to-fees ratio", "LP-12", "reported-figure", "explicit",
     "The paper reports emissions of roughly 30x annual fees (Q1 2026: about $257K fees against about $7.4M staking rewards).", "L142", "~30x", "emissions / fees"),
    ("RL-52", "Illustrated fee-growth paths", "LP-12", "illustration", "illustrative",
     "Tables illustrate 35% and 55% annual fee growth, with USD mint and burn meeting by year 12 or turning net deflationary around year 10.", "L144-167"),
    ("RL-53", "Identity: emission shares sum to 100%", "LP-13", "formula", "explicit",
     "Node, validator and treasury emission shares together are 100% of round emissions.", "L212", "", "", "", "`NodeEmissionShare + ValidatorEmissionShare + TreasuryEmissionShare = 100% of round emissions`"),
    ("RL-54", "NodeEmissionShare", "LP-13 LP-04", "parameter", "proposed-value",
     "Share of round emissions allocated to node operators.", "L231", "94%", "of round emissions", "yes"),
    ("RL-55", "ValidatorEmissionShare", "LP-13 LP-06", "parameter", "proposed-value",
     "Share of round emissions to validators and their delegators, distributed by each validator's delegated stake, with validator reward cuts.", "L232", "1%", "of round emissions", "yes"),
    ("RL-56", "TreasuryEmissionShare", "LP-13 LP-14", "parameter", "proposed-value",
     "Share of round emissions to the DAO treasury.", "L233", "5%", "of round emissions", "yes"),
    ("RL-57", "ValidationScoreContract is swappable", "LP-14 LP-07", "parameter", "explicit",
     "The contract implementing RewardMultiplier scores defaults to a decentralized median of scores and is a governance-swappable address, e.g. to an SPE.", "L90, L222", "decentralized median-of-scores", "", "yes"),
    ("RL-58", "Exclusion: no minimum self-stake", "LP-15 LP-03", "exclusion", "explicit",
     "No minimum self-stake for node operators; it would raise the entry barrier and put stake on hot wallets.", "L179"),
    ("RL-59", "Exclusion: no separate migration or election", "LP-15 LP-06", "exclusion", "explicit",
     "No separate migration or election event; the top N nodes inherit validator slots.", "L180"),
    ("RL-60", "Exclusion: no reward-eligibility ramp", "LP-15 LP-09 LP-03", "exclusion", "explicit",
     "No ramp-up period for new nodes; the 7-round delay is used instead to stop reward theft through inflated fees.", "L181"),
    ("RL-61", "Open question: payment security with unlimited nodes", "LP-16 LP-10", "open-question", "explicit",
     "Securing the PM payment mechanism with an unlimited node count.", "L192"),
    ("RL-62", "Open question: price oracle for emissions", "LP-16 LP-12", "open-question", "explicit",
     "How to secure an onchain LPT price oracle that is not subject to manipulation.", "L194"),
    ("RL-63", "Open question: minimum validator participation", "LP-16 LP-06", "open-question", "explicit",
     "Whether validator compensation should depend on participation, or stake movement alone suffices.", "L196"),
    ("RL-64", "Open question: transferBond vs active delegation", "LP-16 LP-08", "open-question", "explicit",
     "21-round movement of stake inhibits the active delegation market the design wants.", "L105, L198"),
    ("RL-65", "Open question: validator constitution", "LP-16 LP-14", "open-question", "explicit",
     "A validator constitution defining expected validator behavior is referenced but must be written and ratified.", "L200"),
]
PARTS_BY_LP = {r[0]: r[6] for r in LP}
for row in RL:
    rid, cap, concepts, kind, status, inp, lines = row[:7]
    value, unit, gov, formula = (list(row[7:]) + ["", "", "", ""])[:4]
    parts = PARTS_BY_LP[concepts.split()[0]]
    rec(rid, "RL", cap, kind=kind, status=status, in_paper=inp, source_ref=src(lines), concepts=concepts,
        value=value, unit=unit, governance_adjustable=gov, formula=formula, participants=parts)

# ================================================================== VD decisions (existing IDs kept)
# evidence column renamed paper_says; provisions split out into RL links.
VD = {
 "VD-01": dict(caption="Registration and advertising", question="Can an address register and advertise capability, region and price?", classification="G",
   paper_says="Any address may register, with no fixed LPT bond and no node count cap.",
   evidence_needed="A registry admission and advert-verification specification.",
   residual_uncertainty="Registry admission and advert verification mechanics are not specified.",
   authority="Protocol registry and governance for implementation",
   consequence="Open listing and ordinary fee opportunity; no automatic inflation entitlement",
   specification_status="Explicit paper rule; implementation detail missing", follow_up="M1.4 map registry and routing changes",
   owner_milestone="M1.4", concepts="LP-03", provisions="RL-07 RL-08 RL-09", participants="operator governance", lines="L51-54, L175-181"),
 "VD-02": dict(caption="Service selection and routing", question="Which listed service does an agent or customer select?", classification="E",
   paper_says="Discovery and selection use advertised capabilities, regions and prices.",
   evidence_needed="A routing and discovery specification; observations of whether new listings receive traffic.",
   residual_uncertainty="Actual routing, customer preferences, service availability and visibility of new listings are unspecified.",
   authority="Customer or its chosen agent selects; operator supplies advert; validators have no selection authority",
   consequence="Determines who receives customer traffic and whether open listing leads to sales",
   specification_status="Necessary missing detail", follow_up="EX-02 entry study and M1.4 routing map",
   owner_milestone="M1.4", concepts="LP-01 LP-03", provisions="RL-01 RL-08", participants="customer operator", lines="L23-29, L51-54"),
 "VD-03": dict(caption="Settled and attributed payment", question="Was a qualifying USDC customer payment settled and attributed to a node?", classification="D+E+G",
   paper_says="USDC payment at USD prices is explicit; a 50/50 node and network split is proposed.",
   evidence_needed="A settlement record attributable to a node, with rules for reversals and the accounting period.",
   residual_uncertainty="Payment mechanism for unlimited nodes, reversals, fee attribution and accounting period require definition.",
   authority="Payment mechanism; governance sets split",
   consequence="Creates node receipts and the fee input to MFS and BME",
   specification_status="Explicit paper mechanism; necessary settlement detail missing", follow_up="M1.2 claims and M1.4 payment components",
   owner_milestone="M1.2 M1.4", concepts="LP-10 LP-11 LP-04", provisions="RL-32 RL-33 RL-34 RL-61", claims="CL-01 CL-09", participants="customer operator", lines="L111-113, L117-121"),
 "VD-04": dict(caption="Execution and delivery", question="Was the requested service executed and delivered?", classification="E",
   paper_says="Operators do the media work and validators judge whether it was done honestly; payment is a separate event.",
   evidence_needed="Task receipt, execution trace or delivery evidence usable within privacy limits.",
   residual_uncertainty="Task receipt, execution trace, delivery evidence and privacy limits are not specified; completion does not prove correctness.",
   authority="Customer observes receipt; validators may consider execution evidence only under future scoring criteria",
   consequence="Can substantiate work or a specific non-delivery allegation; does not establish correctness or demand",
   specification_status="Explicit work claim; necessary evidence rule missing", follow_up="M1.2 execution evidence; M1.3 delivery scenarios",
   owner_milestone="M1.2 M1.3", concepts="LP-07", provisions="RL-25", claims="CL-02", participants="customer operator validator", lines="L42-49, L85-88"),
 "VD-05": dict(caption="Fee and stake share inputs to MFS", question="What fee share and stake share enter MFS for a node and round?", classification="D+E+G",
   paper_says="Shares are of network totals; measurement windows are governance-adjustable.",
   evidence_needed="A specification of fee and stake snapshots, eligible versus gross fees, zero totals and excluded-node denominators.",
   residual_uncertainty="Fee and stake snapshots, gross versus eligible fees, zero totals and excluded-node denominator remain open.",
   authority="Governance specifies measurement; protocol computes",
   consequence="Changes each node's reward ceiling and possible pool redistribution",
   specification_status="Explicit formula inputs; necessary denominator and window details missing", follow_up="M2 define scenarios; M1.4 identify ledgers",
   owner_milestone="M2 M1.4", concepts="LP-04", provisions="RL-10 RL-12", claims="CL-08 CL-09", participants="operator delegator governance", lines="L55-63, L220"),
 "VD-06": dict(caption="Node entitlement formula (MFS vs appendix)", question="What exact node LPT entitlement is computed before and after the multiplier?", classification="D+G",
   paper_says="Main text: min(fee share, stake share), then median scaling. Appendix: the 94% node share is distributed proportionally to work, weighted by multiplier.",
   evidence_needed="A single accounting specification stating whether 'work' means fee share and the order of min, allocation and weighting.",
   residual_uncertainty="Whether work means fee share and the order of min, allocation and weighting are inconsistent or unstated.",
   authority="Protocol rule chosen through governance",
   consequence="Different formulas change stake cap, payout and incentive results",
   specification_status="Explicit paper formulations in tension; necessary reconciliation", follow_up="M2 workbook sensitivity and M1.4 reward map",
   owner_milestone="M2 M1.4", concepts="LP-04 LP-07 LP-13", provisions="RL-24 RL-54", conflicting_provisions="RL-10 RL-13", participants="operator delegator governance", lines="L55-63, L85-86, L220, L231"),
 "VD-07": dict(caption="Which median applies", question="Which median multiplier applies to a node's eligible round reward?", classification="D+J+G",
   paper_says="Median of active validators' 0-1 scores, taken at claim time.",
   evidence_needed="Rules for score version, precision, absent submissions, challenged scores and ordering against MFS.",
   residual_uncertainty="Score version, precision, absent submissions, challenged scores and order against MFS need rules.",
   authority="Active validators submit judgments; protocol aggregates",
   consequence="Controls claimable node rewards without changing earned USDC fees",
   specification_status="Explicit aggregation; necessary procedural detail missing", follow_up="M1.2 judgment scope and M2 payout cases",
   owner_milestone="M1.2 M2", concepts="LP-07 LP-09", provisions="RL-24 RL-31", claims="CL-07", participants="validator operator", lines="L85-86, L107-109"),
 "VD-08": dict(caption="Validator seat selection", question="Which opt-in node operators hold validator seats?", classification="D+G",
   paper_says="Top N by self plus delegated stake may opt in; proposed N is 33; the next registered node fills a decline.",
   evidence_needed="An election specification: ranking population, snapshots, ties, vacancies and minimum participation.",
   residual_uncertainty="Rank among all nodes versus registered nodes, snapshots, ties, vacancies and minimum participation are unresolved.",
   authority="Governance sets size; registry applies eligibility",
   consequence="Affects reviewer concentration, entrant access and median composition",
   specification_status="Explicit eligibility concept; necessary election detail missing", follow_up="M1.4 election map; later access evaluation",
   owner_milestone="M1.4 M3", concepts="LP-06", provisions="RL-19 RL-20 RL-21", participants="validator operator delegator governance", lines="L79-84, L221"),
 "VD-09": dict(caption="Evidence that warrants a lower score", question="What evidence warrants reducing a node's honesty score?", classification="E+J+G",
   paper_says="Self-dealing, fee fabrication and incorrect results are dishonesty examples; regional or model limits are excluded; published testing evidence is suggested.",
   evidence_needed="A constitution or criteria: proof standard, related-party test, conflict handling, appeal and mapping from finding to score.",
   residual_uncertainty="Constitution, proof standard, related-party criterion, conflict handling, appeals and score severity are not provided; no blanket common-ownership ban follows.",
   authority="Active validators judge cases under future authorized criteria; governance may set procedure or replace score contract",
   consequence="Can deny inflation rewards; error may penalize legitimate work",
   specification_status="Explicit judgment purpose; necessary future criteria and constitution missing", follow_up="M1.2 evidence note and M1.3 legitimate lookalikes",
   owner_milestone="M1.2 M1.3", concepts="LP-07 LP-14", provisions="RL-25 RL-26 RL-65", claims="CL-07 CL-03", participants="validator operator governance", lines="L83-90, L196-200"),
 "VD-10": dict(caption="Median under abstention and disagreement", question="How is the median formed when validators abstain, fail or disagree?", classification="D+J+G",
   paper_says="Each active validator can score each node and the median sets the reward fraction.",
   evidence_needed="Rules for quorum, abstention, default score, even-count medians, conflicts and nonparticipation.",
   residual_uncertainty="Quorum, abstention, default score, even-count median, conflicts and nonparticipation consequences are unspecified.",
   authority="Governance defines rules; active validators provide scores; protocol aggregates",
   consequence="May change or block payout and affects capture resistance",
   specification_status="Explicit median; necessary aggregation procedure missing", follow_up="M1.2 reviewer procedure questions; later validator design",
   owner_milestone="M1.2 M3", concepts="LP-07 LP-06", provisions="RL-23 RL-24 RL-63", participants="validator governance", lines="L81-90, L221-222"),
 "VD-11": dict(caption="Claimability and finality", question="When does an earning-round reward become claimable and final?", classification="D+J+G",
   paper_says="Earliest claim at n+7, using the median current at claim time.",
   evidence_needed="Rules for claim deadline, historical score snapshots, finality and late claims.",
   residual_uncertainty="No claim deadline, historical score snapshot, finality or late-claim treatment is specified.",
   authority="Protocol enforces timing; validators affect current score; governance sets finality",
   consequence="Claim timing can change payout for the same earning round",
   specification_status="Explicit delay and claim-time rule; necessary finality detail missing", follow_up="M2 compare claim times; later dispute design",
   owner_milestone="M2 M3", concepts="LP-09 LP-07", provisions="RL-30 RL-31", claims="CL-07", participants="operator validator", lines="L107-109, L224"),
 "VD-12": dict(caption="Unallocated node emissions", question="What happens to node emissions unallocated by min shares or removed by scores?", classification="D+G",
   paper_says="MFS caps each share and the multiplier can reduce it; the appendix allocates a proposed 94% to nodes.",
   evidence_needed="A budget rule: never minted, held, burned or redistributed.",
   residual_uncertainty="Whether the remainder is never minted, held, burned or redistributed is not stated; renormalization changes caps.",
   authority="Governance specifies budget treatment; protocol executes",
   consequence="Changes actual issuance, rival incentives and supply accounting",
   specification_status="Necessary missing detail inferred from explicit formulas", follow_up="M2 reconcile mint target, allocation and payout",
   owner_milestone="M2", concepts="LP-04 LP-13", provisions="RL-10 RL-24 RL-53 RL-54", participants="operator governance", lines="L55-63, L209-233"),
 "VD-13": dict(caption="Moving bonded stake (transferBond)", question="Can bonded stake move to a new node, and when?", classification="D+G",
   paper_says="21-round unbonding; transferBond eliminated or delayed; the appendix lists 21 rounds including transfers.",
   evidence_needed="A governance choice between the options, with exposure rules across outstanding claims.",
   residual_uncertainty="Removal versus delayed transfer and exposure across outstanding claims remain unsettled.",
   authority="Governance selects rule; staking contract enforces",
   consequence="Affects delegation liquidity and timing of stake backing; no principal slashing specified",
   specification_status="Explicit competing suggestions; policy unresolved", follow_up="M1.4 staking impact and M2 lockup cost assumption",
   owner_milestone="M1.4 M2", concepts="LP-08", provisions="RL-27 RL-64", conflicting_provisions="RL-28 RL-29", participants="delegator operator governance", lines="L92-105, L198, L223"),
 "VD-14": dict(caption="Total authorized mint", question="What total LPT mint is authorized for a period?", classification="D+E+G",
   paper_says="Three alternative concepts are listed; the elaborated concept 1 adds a proposed $50M annual cap.",
   evidence_needed="A selected schedule with LPT price source, period alignment, zero-fee rule and cap conversion.",
   residual_uncertainty="No concept selected; LPT price source, period alignment, zero-fee rule and cap conversion are unresolved.",
   authority="Governance selects schedule and oracle policy; protocol computes",
   consequence="Determines pool size and exposure to reported fee volume",
   specification_status="Explicit open idea draft; necessary schedule decision missing", follow_up="M2 run only selected, clearly labeled variants",
   owner_milestone="M2", concepts="LP-12", provisions="RL-47 RL-48 RL-49 RL-50 RL-62", participants="governance", lines="L128-172, L234-235"),
 "VD-15": dict(caption="USDC fee split", question="How is each settled USDC fee split?", classification="D+G",
   paper_says="Starting BMENodeCut and BMENetworkFee are each proposed at 50% and sum to 100% of gross fees.",
   evidence_needed="Operator cost and margin evidence across workload types.",
   residual_uncertainty="Final values and viability under different workload costs are untested.",
   authority="Governance sets parameters; payment accounting applies them",
   consequence="Controls operator margin and USDC sent to buyback",
   specification_status="Explicit proposed values; economic effect untested", follow_up="M2 cooperative margin case",
   owner_milestone="M2", concepts="LP-11", provisions="RL-33 RL-34 RL-35", participants="operator governance", lines="L117-125, L209-230"),
 "VD-16": dict(caption="Disposition of purchased LPT", question="How is purchased LPT burned or otherwise distributed?", classification="D+E+G",
   paper_says="100% of purchased LPT is burned, separate from the emissions mint; other fee-side cuts start at zero.",
   evidence_needed="One denominator for the fee-side cuts, and execution evidence of actual burn.",
   residual_uncertainty="The identity uses shares of purchased LPT while the notes mention a post-burn pool; a non-100% setting needs one denominator and execution evidence.",
   authority="Governance sets cuts; buyback mechanism executes",
   consequence="Changes actual LPT burn and any treasury or validator receipts",
   specification_status="Explicit starting values; necessary alternative-setting accounting detail missing", follow_up="M2 supply ledger and M1.4 BME components",
   owner_milestone="M2 M1.4", concepts="LP-11", provisions="RL-36 RL-39", conflicting_provisions="RL-37 RL-38", participants="governance", lines="L119-125, L207-212, L228-230"),
 "VD-17": dict(caption="Dividing the validator emission share", question="How is the validator emissions share divided and conditioned on work?", classification="D+G+E",
   paper_says="Main text: 1% of post-BME mint split among active validators. Appendix: 1% of round emissions allocated by delegated stake with cuts.",
   evidence_needed="A compensation rule choosing equal or stake-weighted split, defining post-BME mint and any participation condition.",
   residual_uncertainty="Equal versus stake-weighted split, meaning of post-BME mint and minimum participation are unresolved.",
   authority="Governance sets compensation; protocol measures stake and participation",
   consequence="Changes validator and delegator incentives and seat concentration",
   specification_status="Explicit formulations in tension; necessary participation rule missing", follow_up="M1.2 role duties and M2 accounting cases",
   owner_milestone="M1.2 M2", concepts="LP-13 LP-06", provisions="RL-63", conflicting_provisions="RL-22 RL-55", participants="validator delegator governance", lines="L81-84, L196, L231-233"),
 "VD-18": dict(caption="Buyback price and timing", question="At what price and time is network USDC exchanged for LPT?", classification="D+E+G",
   paper_says="Buyback design is left for research; illustrative TWAP, frequency and slippage parameters are offered.",
   evidence_needed="Execution records of price, timing, deferral and LPT actually burned; an oracle design.",
   residual_uncertainty="Oracle manipulation, execution price, deferred purchases and actual LPT burned remain unverified.",
   authority="Governance sets pool and parameters; executor and market determine fill",
   consequence="USD target equality need not equal token mint/burn equality",
   specification_status="Explicit research gap; implementation and evidence missing", follow_up="M1.4 DEX interface and M2 supply caveat",
   owner_milestone="M1.4 M2", concepts="LP-11 LP-12", provisions="RL-41 RL-42 RL-43 RL-44 RL-45 RL-62", participants="governance", lines="L121-125, L194, L237-246"),
 "VD-19": dict(caption="Does paid execution establish demand or subsidy value?", question="Does real paid execution establish independent demand or worthwhile inflation support?", classification="E+J+G",
   paper_says="Rewards are aimed at real, honest work and self-dealing is a named concern; fee-linked emissions concepts respond to reported fees.",
   evidence_needed="A statement of the reward objective, and any evidence that could establish independent demand or subsidy value beyond payment and execution.",
   residual_uncertainty="Nothing shows that a genuine related-party job is abusive or that execution proves subsidy value; profitability is conditional on full costs and recoveries.",
   authority="Governance defines reward objective; validators judge only authorized dishonesty claims, not general subsidy value",
   consequence="Potential subsidy misallocation even when work is real; no prevalence established",
   specification_status="Unresolved policy question", follow_up="M1.2 claim boundary; M1.3 paired scenario; M2 small example",
   owner_milestone="M1.2 M1.3 M2", concepts="LP-02 LP-04 LP-07 LP-12", provisions="RL-03 RL-25", claims="CL-02 CL-05 CL-06", participants="operator validator governance", lines="L45-49, L85-88, L132-172",
   migration_note="Split: the research hypothesis formerly in this row is now FR-01. The row keeps the unresolved policy question."),
 "VD-20": dict(caption="Outsider access to sales, rewards and seats (split)", question="Can an outsider obtain sales, inflation eligibility and validator access?", classification="E+G", status="split",
   paper_says="Listing and ordinary fees are open without a bond; MFS needs stake for larger rewards; validator seats depend on stake rank and opt-in.",
   residual_uncertainty="Actual routing, customer acquisition, service cost, delegated stake availability and validator concentration are unmeasured.",
   authority="Customers and agents route sales; delegators allocate stake; governance sets validator rules; validators do not gate listing",
   consequence="Open sales can coexist with difficult subsidy or validator access",
   specification_status="Empirical access question, not an unspecified rule", follow_up="Carried by the findings in related",
   concepts="LP-03 LP-04 LP-05 LP-06", provisions="RL-07 RL-11 RL-19", related="FR-02 FR-05 FR-06 FR-10 EX-02", participants="operator customer delegator validator", lines="L51-63, L65-77, L79-86",
   migration_note="Split: an empirical question rather than a rule the paper leaves unspecified. Its parts are carried by FR-02, FR-05, FR-06, FR-10 and the proposed study EX-02. ID retained so old references resolve."),
 "VD-21": dict(caption="Policy authority versus case judgment", question="Who may change policy versus decide an individual honesty case?", classification="G+J",
   paper_says="Parameters are governance-adjustable and the score contract swappable; active validators supply node scores under the default.",
   evidence_needed="A ratified constitution or procedure separating policy changes from case decisions, with limits on replacements.",
   residual_uncertainty="Constitution, limits on replacements and procedural independence are unratified or unstated.",
   authority="Governance or its authorized process changes policy; validators or replacement mechanism score cases",
   consequence="Unbounded or conflated authority could alter reward outcomes and trust assumptions",
   specification_status="Explicit authority outline; necessary governance and procedure details missing", follow_up="M1.2 decision note; later authority boundaries",
   owner_milestone="M1.2 M3", concepts="LP-14 LP-07", provisions="RL-05 RL-57 RL-65", participants="governance validator", lines="L31-38, L88-90, L189-200, L217-235"),
 "VD-22": dict(caption="Correctness of a delivered result", question="Was the delivered result correct under the promised task terms?", classification="E+J+S",
   paper_says="Serving incorrect results is named as dishonesty; AI media jobs are diverse and non-deterministic.",
   evidence_needed="Promised task criteria, acceptable variation, provenance and error attribution for the job type.",
   residual_uncertainty="Promised criteria, acceptable variation, provenance, private input access and error attribution are unspecified; delivery does not prove correctness.",
   authority="Customer assesses its result; validators may score incorrect results under future authorized evidence and severity rules",
   consequence="May support a bounded honesty finding; does not prove independent demand or general economic value",
   specification_status="Explicit dishonesty example; necessary correctness and score criteria missing", follow_up="M1.2 correctness evidence and M1.3 disputed-output lookalikes",
   owner_milestone="M1.2 M1.3", concepts="LP-07", provisions="RL-25", claims="CL-03 CL-07", participants="customer operator validator", lines="L42-49, L85-88"),
}
for rid, f in VD.items():
    lines = f.pop("lines")
    f.setdefault("status", "open")
    rec(rid, "VD", f.pop("caption"), source_ref=src(lines), migrated_from=f"{DRAFT_VD} {rid}", **f)

# ================================================================== CL claims (seed taxonomy)
OPEN12 = "open (M1.2)"
CL = [
    ("CL-01", "Payment settled", "A qualifying USDC payment for the job settled and is attributed to the node.", "MFS", "D+E",
     "customer; node; payment mechanism (VD-03)", "Settlement record attributed to a node; mechanism unspecified (VD-03).",
     "Execution, correctness, independent demand or value to the network.", "LP-10 LP-04", "customer operator", "L111-113, L119",
     "Feeds the fee share (CL-09) through settled fees."),
    ("CL-02", "Executed and delivered", "The requested service was executed and its output delivered.", "none", "E",
     "customer; validators only under future scoring criteria (VD-04)", "Task receipt, execution trace or delivery evidence; none specified (VD-04).",
     "Correctness under promised terms, independent demand or economic value.", "LP-07", "customer operator validator", "L44-45, L86", ""),
    ("CL-03", "Correct under promised terms", "The delivered result was correct under the task terms promised, allowing for variable outputs.", "none", "E+J+S",
     "customer; validators under future criteria (VD-22)", "Promised criteria, acceptable variation and provenance; unspecified (VD-22).",
     "Independent demand or economic value.", "LP-07", "customer operator validator", "L47, L86",
     "An incorrect result can be evidence for a dishonesty finding (CL-07)."),
    ("CL-04", "Available and ready", "The node was available and able to serve the advertised capability when needed.", "none", "open",
     OPEN12, OPEN12, OPEN12, "LP-07 LP-01", "operator customer", "L86",
     "The paper's score does not grade quality of service (RL-25)."),
    ("CL-05", "Independent demand", "The job was bought by a party independent of the node, for its own use.", "none", "E+J",
     OPEN12, OPEN12, OPEN12, "LP-04 LP-02 LP-12", "customer operator", "L47", ""),
    ("CL-06", "Economic value of subsidy", "Inflation paid for the job buys a benefit to the network worth its cost.", "none", "E+J+G",
     OPEN12, OPEN12, OPEN12, "LP-02 LP-12", "governance", "L35, L63", ""),
    ("CL-07", "Dishonesty finding", "The node acted dishonestly: self-dealing, fee fabrication or serving incorrect results.", "multiplier", "E+J+G",
     "active validators (RL-23)", "Published testing and monitoring evidence or other surfaced criteria (RL-26); proof standard unspecified (VD-09).",
     "General service quality or uptime (RL-25). Related-party work can be genuine; a finding does not by itself settle subsidy value (VD-19).",
     "LP-07", "validator operator", "L86-88", ""),
    ("CL-08", "Stake share", "The node holds a given share of total self plus delegated stake in the measurement window.", "MFS", "D+G",
     "protocol staking ledger", "Stake snapshot under a governed window (VD-05).",
     "That the node does real work: stake alone cannot tell self-dealing from real usage (L47).", "LP-04 LP-05", "operator delegator", "L55-61, L220", ""),
    ("CL-09", "Fee share", "The node earned a given share of network fees in the measurement window.", "MFS", "D+E+G",
     "protocol and payment accounting", "Settled fees attributed to the node under a governed window (VD-05).",
     "Honest work, independent demand or subsidy value (VD-19).", "LP-04 LP-10", "operator", "L55-61, L220", ""),
]
for rid, cap, claim, rin, cls, obs, ev, dne, concepts, parts, lines, note in CL:
    rec(rid, "CL", cap, status="seed", claim=claim, reward_input=rin, classification=cls, observers=obs,
        evidence_types=ev, does_not_establish=dne, concepts=concepts, participants=parts, source_ref=src(lines),
        migrated_from=f"{DRAFT_MAP} (validator-judgment table; claim distinctions)", migration_note=note or None)

# ================================================================== FR findings register
FR = [
    ("FR-01", "Self-funded real usage", "hypothesis",
     "If an emissions rule or a node's share of rewards responds to paid fees, a party could pay itself for real, correctly executed work and collect more reward than the job cost. Execution evidence would confirm the work but not independent demand or a worthwhile subsidy.",
     "The paper names self-dealing as a concern (L47, L86) and relies on MFS stake caps (L63) and a cap on network-wide mint (L172). Common ownership alone is not misconduct. No profitability calculation or prevalence observation exists yet.",
     "Profitability depends on fee diversion, resource cost, stake ceiling, collectible LPT value, burn and buyback effects, other recoveries, validator response and the emissions rule. A small example showing the cycle unprofitable under the paper's own parameters would weaken it; a binding cap limits pool growth but not within-pool allocation.",
     "Proving execution would not settle whether a reward is worth paying.",
     "What must reward eligibility establish beyond settled payment and correct execution? (M1.2)",
     "LP-04 LP-07 LP-12 LP-02", "RL-03 RL-10 RL-25 RL-47 RL-50", "VD-19 VD-14", "CL-02 CL-05 CL-06", "", "operator validator governance",
     "L45-49, L63, L86, L132-172", f"{DRAFT_MAP} (conditional economic concern); {DRAFT_VD} VD-19"),
    ("FR-02", "Open listing is an entry benefit already in the paper", "inference",
     "No-bond, uncapped registration with uncapped ordinary fees removes any formal insider-only barrier to listing and selling. Whether outsiders can actually find customers is unmeasured.",
     "Explicit provisions RL-07, RL-09, RL-11 and the exclusion of minimum self-stake (RL-58).",
     "A working implementation with open routing would confirm usable access; routing or onboarding that favors incumbents would weaken it in practice.",
     "Entry concerns must be about rewards, seats or practical friction, not formal permission to sell.", "",
     "LP-03 LP-15", "RL-07 RL-09 RL-11 RL-58", "VD-01", "", "", "operator customer", "L51-63, L175-181", f"{DRAFT_GE} GE-01"),
    ("FR-03", "USDC pricing may ease quote comparison", "hypothesis",
     "USD prices paid in USDC may make quotes easier to compare than ETH-denominated fees.",
     "USDC payment and USD pricing are explicit (RL-32); the usability effect is untested.",
     "Wallet and funding friction could offset pricing clarity; measure full customer setup and transaction experience.",
     "", "", "LP-10", "RL-32", "", "", "EX-02", "customer", "L111-113", f"{DRAFT_GE} GE-02"),
    ("FR-04", "Broad scope may widen supplier and buyer set", "hypothesis",
     "API passthrough and broad media capability scope expand the possible set of suppliers and buyers.",
     "The scope is explicit (RL-02); uptake is unmeasured.",
     "Test real supported interfaces and buyers' ability to combine services.",
     "", "", "LP-01", "RL-01 RL-02", "", "", "", "operator customer", "L23-29", f"{DRAFT_GE} GE-03"),
    ("FR-05", "Stake-linked reward gap for understaked entrants", "inference",
     "An entrant whose fee share exceeds its stake share earns less inflation than an equally used, adequately staked node. This is a possible economic disadvantage, not a ban or evidence of incumbent capture.",
     "Arithmetic from MFS, assuming the same eligible-fee window, multiplier and emission pool (EX-01.F13: 5% of fees with 1% versus 5% of stake gives 1% versus 5% of the node allocation).",
     "If fees alone cover viable margins the gap may not matter. The paper expects stake to move toward high-fee understaked nodes (L63, L69), and delegation can close the gap; it also rejects minimum self-stake and a reward ramp, both favorable to entry.",
     "Reward competitiveness, not sales access, is where entry could be disadvantaged.",
     "How quickly does delegation reach productive understaked nodes? (M2)",
     "LP-04 LP-05 LP-03", "RL-10 RL-11 RL-16 RL-58 RL-60", "VD-05", "CL-08 CL-09", "EX-01 EX-02", "operator delegator",
     "L55-71, L175-181", f"{DRAFT_GE} GE-04"),
    ("FR-06", "Reputation and relationships may favor incumbents", "hypothesis",
     "Reputation, relationships and existing stake could reinforce an incumbent's advantage in attracting delegation and traffic.",
     "Unmeasured; prompted by the delegation provisions.",
     "Compare matched new and established offers; do not infer insider status or concentration from the formula alone.",
     "", "", "LP-05 LP-03", "RL-15 RL-16", "", "", "EX-02", "operator delegator", "L65-77", f"{DRAFT_GE} GE-05"),
    ("FR-07", "A 50% network fee can squeeze API resale margins", "inference",
     "Under the starting split, a relay paying a large share of its price upstream can lose money per job unless it raises price or cuts cost.",
     "Arithmetic under the proposed split: EX-01.F8, EX-01.F11 and EX-01.F12.",
     "Price flexibility, cheaper upstream supply, added value, a changed cut or other revenue may keep a service viable. Customer willingness to pay is unknown.",
     "The proposed split matters most for pass-through businesses.", "",
     "LP-11 LP-01", "RL-02 RL-33 RL-34", "VD-15", "", "EX-01", "operator customer", "L117-121, L226-227", f"{DRAFT_GE} GE-06"),
    ("FR-08", "Lockup and claim delay may slow financing", "hypothesis",
     "A 21-round stake transfer wait and 7-round reward delay may slow entrants' financing and delegators' experimentation.",
     "The timing proposals are explicit; the behavioral effect is untested.",
     "Measure actual redelegation and cash-flow decisions. The delays can also deter rapid abuse and protect trust.",
     "", "", "LP-08 LP-09 LP-05", "RL-27 RL-29 RL-30 RL-64", "VD-11 VD-13", "", "", "operator delegator", "L92-109", f"{DRAFT_GE} GE-07"),
    ("FR-09", "Top-stake scoring may affect perceived fairness", "hypothesis",
     "Honesty scoring by top-stake validators may affect entrants' perceived fairness and reward certainty.",
     "Scoring and selection are explicit; the effect on entry is untested.",
     "Defined evidence, recusal, appeal and outcome records could reduce uncertainty. Listing and ordinary fees stay open regardless.",
     "", "", "LP-06 LP-07", "RL-19 RL-23 RL-24", "VD-09 VD-10", "CL-07", "", "operator validator", "L79-90", f"{DRAFT_GE} GE-08"),
    ("FR-10", "Practical access cannot yet be assessed", "inference",
     "Onboarding, discovery ranking, service specifications, payment security with unlimited nodes and score procedures must be specified before practical access can be evaluated.",
     "The paper leaves these open (L51-53, L189-200).",
     "Inspect specifications and run fresh-user journeys once an implementation exists.",
     "", "", "LP-03 LP-16 LP-01", "RL-08 RL-61 RL-65", "VD-02 VD-03 VD-09", "", "EX-02", "customer operator", "L51-53, L189-200", f"{DRAFT_GE} GE-09"),
    ("FR-11", "Shared evidence tooling may lower newcomers' burden", "hypothesis",
     "Publicly funded testing, monitoring and published evidence could reduce the investigation burden for newcomers as well as established participants.",
     "The public-good tooling proposal is explicit (RL-26); accessibility is unmeasured.",
     "Test whether outsiders can find and interpret the evidence and understand score decisions from public information; separate missing tooling from unclear scoring policy.",
     "", "", "LP-07", "RL-26", "", "CL-07", "EX-02", "operator validator", "L86-88", f"{DRAFT_GE} GE-10"),
    ("FR-12", "Discovery lets capable new nodes win customers", "assumption",
     "Discovery and routing let capable new nodes obtain customers, and service cost supports the quoted price.",
     "", "Observed routing of new listings and operator cost data.", "", "",
     "LP-01 LP-03", "RL-01 RL-08", "VD-02", "", "EX-02", "customer operator", "L21-29, L51-54", f"{DRAFT_MAP} objectives table"),
    ("FR-13", "Settled fees track meaningful work", "assumption",
     "Settled fees track meaningful work well enough to allocate inflation rewards.",
     "", "Self-funded or fabricated fees that pass as real work would weaken it (FR-01).", "", "",
     "LP-02 LP-04", "RL-03 RL-10", "VD-05", "CL-09 CL-05", "", "operator", "L31-38, L55-63", f"{DRAFT_MAP} objectives table"),
    ("FR-14", "Validators can separate dishonesty from honest work", "assumption",
     "Validators can identify disqualifying conduct without suppressing honest work.",
     "", "Legitimate lookalikes (M1.3) that validators cannot distinguish would weaken it.", "", "",
     "LP-07", "RL-25 RL-26", "VD-09 VD-22", "CL-07 CL-03", "", "validator operator", "L79-88", f"{DRAFT_MAP} objectives table"),
    ("FR-15", "Delegators can evaluate and move stake in time", "assumption",
     "Delegators can compare performance, move capital with acceptable delay and bear the stated exposure.",
     "", "Lockup cost and information limits observed in practice (FR-08).", "", "",
     "LP-05 LP-08", "RL-15 RL-16 RL-27", "VD-13", "", "", "delegator", "L65-77, L92-105", f"{DRAFT_MAP} objectives table"),
    ("FR-16", "Buybacks execute well and burn balances mint", "assumption",
     "Buybacks execute at acceptable prices and actual LPT burned balances actual LPT minted over time.",
     "", "Execution records; an LPT-quantity rather than USD comparison (FR-25).", "", "",
     "LP-11 LP-12", "RL-36 RL-41 RL-46", "VD-16 VD-18", "", "", "governance", "L111-125, L128-172", f"{DRAFT_MAP} objectives table"),
    ("FR-17", "Scoring rules make judgments credible and timely", "assumption",
     "Evidence, participation, conflict and timing rules make validator judgments credible and timely.",
     "", "Unanswered procedure questions (VD-09, VD-10, VD-11) weaken it until specified.", "", "",
     "LP-06 LP-07 LP-09", "RL-19 RL-24 RL-31", "VD-09 VD-10 VD-11", "CL-07", "", "validator", "L79-90, L107-109", f"{DRAFT_MAP} objectives table"),
    ("FR-18", "Oracle and windows can be specified without circularity", "assumption",
     "Price oracle, measurement periods and governance choices can be specified without making supply or incentive claims circular.",
     "", "An emissions rule whose inputs can be moved by the parties it rewards would weaken it.", "", "",
     "LP-12 LP-14", "RL-12 RL-50 RL-62", "VD-14", "", "", "governance", "L35-38, L128-172, L189-200", f"{DRAFT_MAP} objectives table"),
    ("FR-19", "Paper rationale: MFS limits self-dealing by low-stake nodes", "assumption",
     "Because stake caps reward share, self-dealt fees earn a low-stake node little; faking fee volume beyond true stake share earns nothing.",
     "Paper reasoning (L63, L172).",
     "A party with enough stake, or with self-delegated stake, is not limited by the cap; this is the case FR-01 examines.", "", "",
     "LP-04", "RL-10 RL-11", "", "CL-08 CL-09", "EX-01", "operator delegator", "L63, L172", ""),
    ("FR-20", "Paper rationale: stake rank makes validator takeover costly", "assumption",
     "Selecting validators by stake rank makes it expensive to take over most of the set and attack reward integrity.",
     "Paper reasoning (L73).",
     "Coordination among high-stake nodes, or a small number of seats held by one interest, would weaken it (SC-09).", "", "",
     "LP-06 LP-05", "RL-19 RL-20", "VD-08 VD-10", "", "", "validator delegator", "L73, L83", ""),
    ("FR-21", "Paper rationale: the 7-round delay lets validators catch spikes", "assumption",
     "A 7-round window gives validators time to observe a fee spike, investigate and drive the median to zero before the reward is claimable.",
     "Paper reasoning (L109); used in place of a reward ramp (L181).",
     "Detection and scoring that take longer than 7 rounds, or claim-time scoring that later reverses (VD-11), would weaken it.", "", "",
     "LP-09 LP-07", "RL-30 RL-31 RL-60", "VD-11", "CL-07", "", "validator operator", "L109, L181", ""),
    ("FR-22", "Paper rationale: 21-round lockup deters hit-and-run identities", "assumption",
     "A 21-round lockup stops malicious nodes from quickly unbonding and re-registering under new identities.",
     "Paper reasoning (L96-99).",
     "If extractable reward exceeds the lockup cost, the deterrent fails; the paper judges 7 rounds too short on this basis.", "", "",
     "LP-08", "RL-27 RL-28 RL-29", "VD-13", "", "", "operator delegator", "L94-103", ""),
    ("FR-23", "A binding cap stops pool growth, not share-grabbing", "inference",
     "Once the annual cap binds, extra fee volume, real or fabricated, funds burn without enlarging total rewards; it does not stop a node taking a larger share of a fixed pool.",
     "Stated in the paper's own analysis (L168-172).",
     "Below the cap, fee-linked concepts still let reported fees enlarge the pool.",
     "Within-pool allocation still rests on MFS, scoring and the delay.", "",
     "LP-12 LP-04", "RL-47 RL-50", "VD-14", "", "", "governance operator", "L168-172", f"{DRAFT_MAP} (emissions concepts)"),
    ("FR-24", "MFS leaves part of the node envelope unassigned", "inference",
     "When fee and stake shares are misaligned across nodes, min shares sum to less than 100% and part of the node envelope is unassigned; its disposition is unspecified.",
     "EX-01.F2: 90/10 fees against 10/90 stake leaves 752 of 940 LPT unassigned (illustrative, fixed envelope).",
     "A rule that renormalizes or redistributes the remainder would remove the gap but change the stake caps (VD-12).", "", "",
     "LP-04 LP-13", "RL-10 RL-54", "VD-12 VD-06", "", "EX-01", "operator governance", "L55-63, L231", f"{DRAFT_MAP}; {DRAFT_EX} README"),
    ("FR-25", "USD burn = mint does not establish LPT equilibrium", "inference",
     "The paper's tables compare mint and burn in USD; equal USD amounts need not mean equal LPT minted and burned.",
     "Tables in L146-165 are USD-denominated; LPT price, oracle and execution are open (RL-41, RL-62).",
     "An LPT-quantity ledger with execution prices would test it.", "", "",
     "LP-12 LP-11", "RL-46 RL-52 RL-62", "VD-18 VD-14", "", "", "governance", "L142-167", f"{DRAFT_VD} VD-18 consequence"),
]
for (rid, cap, status, stmt, ev, wc, impl, dq, concepts, provisions, decisions, claims, exps, parts, lines, mfrom) in FR:
    rec(rid, "FR", cap, status=status, statement=stmt, evidence=ev, would_change=wc, implication=impl, design_question=dq,
        concepts=concepts, provisions=provisions, decisions=decisions, claims=claims, experiments=exps,
        participants=parts, source_ref=src(lines), migrated_from=mfrom)

# ================================================================== SC scenario seeds
OPEN13 = "open (M1.3)"
SC = [
    ("SC-01", "Outside customer buys a listed capability", "cooperative", "",
     "An outside app or agent discovers a listed node and buys a chosen capability at its USD quote, paying USDC.",
     "The payment adds to the node's fee share; the customer needs no stake or validator seat (L53, L113).",
     "Onboarding, wallet custody, API contracts, service comparison, routing and remedies are unspecified.",
     "LP-01 LP-03 LP-10", "CL-01 CL-02", "VD-02 VD-03", "customer operator", "L23-29, L51-54, L111-113", "journey: outside customer or app"),
    ("SC-02", "API passthrough operator lists and sells", "cooperative", "",
     "An existing external API seller registers without a bond, advertises price, region and capability, and resells upstream work.",
     "It earns ordinary fees at once; MFS caps its inflation share at its stake share; the node cut applies to an upstream-cost business (L53-61, L119).",
     "How evidence distinguishes permitted upstream fulfillment from inaccurate output, price manipulation or related-party use is unsettled.",
     "LP-01 LP-03 LP-04 LP-11", "CL-01 CL-09", "VD-01 VD-15", "operator", "L26, L51-63, L117-121", "journey: external API seller"),
    ("SC-03", "New GPU provider lists and competes", "cooperative", "",
     "A new GPU provider lists without minimum self-stake and competes for fees; hardware and operating costs precede uncertain sales.",
     "No node cap or self-stake requirement (L53, L179); delegation may be needed for an inflation share matching its fee share (L69).",
     "Discovery and quality evidence may shape routing even without formal approval.",
     "LP-03 LP-04 LP-05", "CL-08 CL-09", "VD-01 VD-02 VD-05", "operator delegator", "L51-69, L179", "journey: new GPU provider"),
    ("SC-04", "New delegator backs a node", "cooperative", "",
     "A new delegator bonds to a node, shares its reward and fee terms and looks for understaked performers.",
     "Stake raises the node's reward ceiling (L69); moving it later takes 21 rounds and rewards arrive after 7 (L94, L109).",
     "Information needed to evaluate a new operator and the effects of changing delegation are not fully specified.",
     "LP-05 LP-08 LP-09", "CL-08", "VD-13 VD-11", "delegator operator", "L65-77, L92-109", "journey: new delegator"),
    ("SC-05", "Top-staked operator opts in as validator", "cooperative", "",
     "An operator in the top-staked eligible set registers as a validator and scores other nodes.",
     "It becomes active by registering and shares the validator emission allocation (L81-84, L221, L232).",
     "Evidence standards, conflicts, quorum and score recourse need definition.",
     "LP-06 LP-07 LP-13", "CL-07", "VD-08 VD-09 VD-10 VD-17", "validator operator", "L79-88, L221, L232", "journey: prospective validator"),
    ("SC-06", "Related-party real work", "lookalike", "SC-07",
     "An operator's affiliate buys real jobs from it for genuine internal production and pays the listed price.",
     "Fees count toward fee share, capped by stake (L57-61); validators may score self-dealing, but no related-party test exists (L86).",
     "Common ownership alone is not misconduct; the paper does not define when related-party work is self-dealing.",
     "LP-04 LP-07", "CL-01 CL-02 CL-05", "VD-09 VD-19", "operator validator", "L47, L57-61, L86", "pair: related-party real work"),
    ("SC-07", "Self-funded reward farming with real jobs", "adversarial", "SC-06",
     "A party pays its own node for real, correctly executed jobs because the inflation reward exceeds the job's cost.",
     "MFS caps the reward at stake share (L63); validators may score self-dealing (L86); a binding cap limits pool growth but not share (L172).",
     "Execution evidence is identical to SC-06; what distinguishes the cases is independent demand and subsidy value, which no rule defines.",
     "LP-04 LP-07 LP-12", "CL-02 CL-05 CL-06 CL-07", "VD-19 VD-09 VD-14", "operator validator governance", "L47, L63, L86, L168-172", "pair: self-funded reward farming"),
    ("SC-08", "New node seeks delegation", "market-pressure", "SC-09",
     "A productive but understaked node tries to attract delegation so its inflation share can rise toward its fee share.",
     "Delegators are expected to move stake toward such nodes (L63, L69).",
     "Delegators' information, lockup and competition with incumbents' relationships are unspecified (FR-06, FR-08).",
     "LP-05 LP-04 LP-06", "CL-08 CL-09", "VD-13", "operator delegator", "L63, L69", "pair: new node seeking delegation"),
    ("SC-09", "Coordinated validators zero a competitor", "adversarial", "SC-08",
     "A coordinated group of high-stake validators scores a competing node down to reduce its rewards.",
     "The paper names this risk and relies on mutual accountability and stake cost (L73, L83).",
     "Conflict rules, appeal and the evidence needed to justify a score are unspecified (VD-09, VD-10, VD-21).",
     "LP-06 LP-07 LP-14", "CL-07", "VD-09 VD-10 VD-21", "validator operator", "L73, L83, L86", "pair: stake-driven capture"),
    ("SC-10", "Disputed non-deterministic output", "lookalike", "SC-11",
     "A customer or validator disputes an AI media output that varies legitimately between runs.",
     "Validators should not penalize legitimate performance limits (L86); the paper acknowledges non-deterministic job types (L47).",
     "No promised-terms criteria or acceptable-variation standard exists (VD-22).",
     "LP-07", "CL-02 CL-03", "VD-22 VD-09", "customer operator validator", "L47, L86", "pair: disputed non-deterministic output"),
    ("SC-11", "Incorrect result served", "adversarial", "SC-10",
     "A node serves results that are wrong under the promised task terms while collecting fees.",
     "Serving incorrect results is named dishonesty that the score should catch (L86).",
     "Proof standard and severity mapping from finding to score are unspecified (VD-09).",
     "LP-07", "CL-03 CL-07", "VD-22 VD-09", "operator validator", "L86", "pair: incorrect result"),
    ("SC-12", "API relay under a 50% network fee", "market-pressure", "SC-13",
     "A relay whose upstream cost is a large share of its price faces the proposed 50% network fee.",
     "The split applies uniformly (L119); the node keeps its uncapped fees but may earn a thin or negative margin (EX-01.F8).",
     "Whether a relay can raise prices or add value is unknown (FR-07).",
     "LP-11 LP-01", "CL-01", "VD-15", "operator customer", "L26, L117-121", "pair: API relay at 50% cut"),
    ("SC-13", "Relay price manipulation", "adversarial", "SC-12",
     "A relay's pricing conduct is alleged to be manipulative.",
     OPEN13,
     "The draft names price manipulation without defining it; M1.3 must define the conduct or drop the case.",
     "LP-11 LP-07", "CL-07", "VD-09", "operator validator", "L86, L119", "pair: price manipulation"),
    ("SC-14", "Honest delayed claim", "lookalike", "SC-15",
     "A node claims an old round's reward later than n+7 for ordinary operational reasons.",
     "The median current at claim time applies (L109).",
     "Without a claim deadline or score snapshot, the same round can pay differently depending on claim time (VD-11).",
     "LP-09 LP-07", "CL-07", "VD-11 VD-07", "operator", "L107-109, L224", "pair: honest delayed claim"),
    ("SC-15", "Claim timed to a changed median", "adversarial", "SC-14",
     "A node times its claim to a period when its median score is higher than when the round was investigated.",
     "The claim-time median applies (L109); no rule addresses timing.",
     "Whether this is possible or profitable is a question for testing, not established exploitation (VD-11).",
     "LP-09 LP-07", "CL-07", "VD-11 VD-07", "operator validator", "L107-109, L224", "pair: late claim under changed median"),
    ("SC-16", "Single-round fee spike", "adversarial", "",
     "A node spikes its apparent fees in one round, hoping to claim a large reward before validators react.",
     "Named by the paper as the most concrete attack; the 7-round delay lets validators investigate and zero the median before the reward is claimable (L109).",
     "The legitimate lookalike (a genuine fee spike) is not defined; detection within 7 rounds is assumed (FR-21).",
     "LP-09 LP-07 LP-04", "CL-07 CL-09", "VD-11", "operator validator", "L109, L181", ""),
]
for (rid, cap, typ, pair, sit, outcome, amb, concepts, claims, decisions, parts, lines, origin) in SC:
    rec(rid, "SC", cap, status="seed", sc_type=typ, pair_with=pair, situation=sit, observable=OPEN13,
        litepaper_outcome=outcome, ambiguity=amb, concepts=concepts, claims=claims, decisions=decisions,
        participants=parts, source_ref=src(lines),
        migrated_from=(f"{DRAFT_GE if origin.startswith('journey') else DRAFT_MAP} ({origin})" if origin else None))

# ================================================================== EX experiments and fixtures
rec("EX-01", "EX", "Baseline accounting workbook", status="reproducible",
    question="How do the paper's proposed fee split, emission shares, MFS and multiplier allocate one round's fees and an entered LPT envelope between two cooperative nodes?",
    inputs="Entered emission envelope 1,000 LPT per round (analytical control, not an emissions policy); 94/1/5 emission shares; 50/50 fee split; 2 USDC/LPT illustrative buyback price; two nodes with editable fees, stake, scores, fee and reward cuts and costs.",
    method="XLSX workbook generated by build.py; verify.py checks independent Python arithmetic against saved formulas and caches; recalculate.py optionally recalculates in LibreOffice.",
    formula="node entitlement = envelope × NodeEmissionShare × min(fee share, stake share) × multiplier (reconstruction of RL-10, RL-24, RL-54; VD-06 open). No normalization; MFS gap and score-withheld amounts shown separately.",
    results="Fixtures below (illustrative). verify.py on 2026-09-28: 7 arithmetic fixtures PASS; 222 saved formulas cached; default and 14 sensitivity rows PASS.",
    limits="Does not test a fee-linked emissions schedule, validator judgments, buyback execution, execution, correctness, availability, demand or value. The entered envelope is not an established mint. Costs are illustrative. No principal loss is modeled.",
    reproduce="uv run --no-project --with xlsxwriter==3.2.9 --with openpyxl==3.1.5 python3 experiments/m1/baseline-accounting/verify.py",
    repo_path="experiments/m1/baseline-accounting/ (build.py, verify.py, recalculate.py, README.md); deliverables/m1/litepaper-baseline-accounting.xlsx",
    provisions="RL-10 RL-24 RL-33 RL-34 RL-36 RL-53 RL-54 RL-55 RL-56", decisions="VD-05 VD-06 VD-12 VD-15",
    concepts="LP-04 LP-07 LP-11 LP-13", participants="operator delegator", source_ref=src("L55-63, L84-86, L117-121, L207-233"),
    migrated_from=f"{DRAFT_EX} v0.3; litepaper-baseline-accounting.xlsx",
    migration_note="The workbook's 'Source & decisions' sheet duplicates VD records; the records here replace it once the workbook is regenerated.")

rec("EX-02", "EX", "Entry journey study", status="proposed",
    question="Under stated interpretations of the paper, can outside buyers, API relays, GPU sellers, delegators and validator aspirants complete their journeys from public information, and where do they meet avoidable friction or newcomer-relative disadvantage?",
    method="Give competent outside participants only public instructions; log rule sources, missing knowledge, help requests, retries and abandonment. Compare buyers against a documented direct route, and newcomer against matched established sellers. Record ordinary fees and inflation rewards separately. Where the paper leaves a step unspecified, record the gap rather than filling it.",
    limits="No participants, services, thresholds, dates or outcomes exist or are assumed. Stop when each material gate has a mechanism, counterexample or evidence limit; do not infer prevalence.",
    concepts="LP-01 LP-03 LP-04 LP-05 LP-06", decisions="VD-02", participants="customer operator delegator validator",
    source_ref=src("L21-29, L51-109"), migrated_from=f"{DRAFT_GE} (small follow-up study, proposed only)")

FX = [
    ("EX-01.F1", "Aligned 60/40 fees and stake", "verify.py", "Fees 600/400 USDC; stake 600/400 LPT; scores 1/1.", "Paid 564/376 LPT (940 total); MFS gap 0; withheld 0.", "LP-04"),
    ("EX-01.F2", "Misaligned 90/10 fees vs 10/90 stake", "verify.py", "Fees 900/100; stake 100/900; scores 1/1.", "MFS 10%/10%; paid 94/94 LPT (188 total); 752 LPT of the 940 node envelope unassigned.", "LP-04"),
    ("EX-01.F3", "Node A score 0.5", "verify.py", "Fees 600/400; stake 600/400; scores 0.5/1.", "Paid 282/376 LPT (658 total); 282 LPT withheld by score.", "LP-07"),
    ("EX-01.F4", "Node A zero stake", "verify.py", "Fees 600/400; stake 0/1000; scores 1/1.", "A: 0 LPT but 300 USDC node-side receipt; B: 376 LPT; MFS gap 564 LPT.", "LP-04 LP-03"),
    ("EX-01.F5", "Zero network fees", "verify.py", "Fees 0/0; stake 600/400.", "MFS and rewards undefined (needs rule).", "LP-04"),
    ("EX-01.F6", "Zero network stake", "verify.py", "Fees 600/400; stake 0/0.", "MFS and rewards undefined (needs rule).", "LP-04"),
    ("EX-01.F7", "Zero fees and zero stake", "verify.py", "Fees 0/0; stake 0/0.", "MFS and rewards undefined (needs rule).", "LP-04"),
    ("EX-01.F8", "Pass-through margin, one job", "verify.py", "Price 1 USDC; upstream 0.40; other cost 0.02; node cut 50%; operator fee retention 80% (assumed).", "Operator receipt 0.40 USDC; margin -0.02 USDC; break-even price 1.05 USDC.", "LP-11"),
    ("EX-01.F9", "Default buyback and burn", "hand", "Gross fees 1,000 USDC; network fee 50%; 2 USDC/LPT illustrative price.", "500 USDC funds BME; 250 LPT purchased and burned. Validator and treasury envelopes 10 and 50 LPT.", "LP-11 LP-13"),
    ("EX-01.F10", "Cooperative seller, $1 job", "hand", "Price $1; 50/50 split; operator keeps full node portion before delegator sharing.", "$0.50 to the operator before costs; $0.50 to buy-and-burn.", "LP-11"),
    ("EX-01.F11", "API relay with $0.60 upstream cost", "hand", "Price $1; 50/50 split; upstream $0.60.", "Loss of $0.10 per job before other costs.", "LP-11"),
    ("EX-01.F12", "Break-even for $1 upstream cost", "hand", "Upstream $1; no other costs; 50/50 split.", "Customer price $2 reaches break-even only.", "LP-11"),
    ("EX-01.F13", "Competitive entrant, 5% of fees", "hand", "Two honest nodes each with 5% of eligible fees and full scores; stake 1% versus 5%.", "Entitled to 1% versus 5% of the node allocation; equal ordinary fees.", "LP-04 LP-05"),
]
for rid, cap, by, inputs, expected, concepts in FX:
    rec(rid, "FX", cap, status="illustrative", checked_by=by, inputs=inputs, expected=expected, experiments="EX-01", concepts=concepts,
        migrated_from=(f"{DRAFT_EX}/verify.py" if by == "verify.py" else f"{DRAFT_GE} (economics section)" if rid >= "EX-01.F10" and rid != "EX-01.F9" else f"{DRAFT_EX}/README.md"))

# ================================================================== pilot filter
if "--pilot" in sys.argv:
    PILOT_LP = {"LP-03", "LP-04", "LP-07"}
    keep = set()
    for r in R:
        cs = set(r.get("concepts", "").split())
        if r["title"] in PILOT_LP or (cs & PILOT_LP):
            keep.add(r["title"])
    # close over references so the pilot has no dangling links
    changed = True
    while changed:
        changed = False
        for r in R:
            if r["title"] in keep:
                for fld in ("concepts", "provisions", "conflicting_provisions", "decisions", "claims", "findings",
                            "scenarios", "pair_with", "experiments", "components", "related"):
                    for ref in r.get(fld, "").split():
                        if ref not in keep:
                            keep.add(ref); changed = True
    R = [r for r in R if r["title"] in keep]

json.dump(R, sys.stdout, indent=1, ensure_ascii=False)
